name: DPWT Marcel Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # läuft jede Stunde

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: |
          python main.py
