name: DPWT Marcel Bot Scheduler

on:
  schedule:
    # 1x täglich um 08:00 UTC -> prüft, ob ein Turnier ansteht
    - cron: '0 8 * * *'
    # stündlich -> aktualisiert laufendes Turnier
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-tournament:
    if: github.event.schedule == '0 8 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install requests beautifulsoup4

      - name: Run Tournament Checker
        run: python tournament_checker.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  run-bot:
    if: github.event.schedule == '0 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install requests beautifulsoup4

      - name: Run Main Bot
        run: python main.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}